enhavo_navigation_admin_navigation_index:
    path: /navigation/index
    defaults:
        _expose: admin
        _vue:
            component: resource-index
            groups: admin
            meta:
                api: enhavo_navigation_admin_api_navigation_index
        _endpoint:
            type: admin

enhavo_navigation_admin_navigation_create:
    path: /navigation/create
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_navigation_admin_api_navigation_create
        _endpoint:
            type: admin

enhavo_navigation_admin_navigation_update:
    path: '/navigation/update/{id}'
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_navigation_admin_api_navigation_update
        _endpoint:
            type: admin
